import {writeFileSync} from 'node:fs';
import {json,dataRoot} from '../assets/import-complete-edition-c1a.mjs';
import {semanticCategories} from './c1ar-quest-classification.mjs';
const escape=s=>String(s).replaceAll('|','\\|');
export function buildRepairReport(definitions,evidence){
 const rules=definitions.flatMap(n=>n.specialRules);
 const special=definitions.filter(n=>n.specialRules.length);
 const kind=n=>n.sourceStatus==='source-blocked'?'source-blocked':n.specialRules.every(r=>r.affectsObjectiveCompletion)?'objective-affecting only':n.specialRules.every(r=>!r.affectsObjectiveCompletion)?'non-objective only':'mixed';
 const cell=n=>{const e=evidence.find(e=>e.definitionId===n.id);return `${e.deckId}-${e.cardIndex}`;};
 const lines=[
 '# C1A-R — Quest Semantic Classification Repair',
 '',
 'Status: semantic repair complete; independent audit pending. STOP at C1A-R. C1B Production Integration is not authorized by this report.',
 '',
 'Branch: `phase-11a4-c1ar-quest-semantic-classification-repair`. Frozen base: `300c0a84ed1e5bd2025128fd4e35eeed0b600a06`.',
 '',
 '## Coverage',
 '',
 '| Metric | Count |','| --- | ---: |',
 `| Quest definitions | ${definitions.length} |`,
 `| With Special Rules | ${special.length} |`,
 `| Without Special Rules | ${definitions.length-special.length} |`,
 `| Source-supported | ${definitions.filter(n=>n.sourceStatus==='source-supported').length} |`,
 `| Source-blocked | ${definitions.filter(n=>n.sourceStatus==='source-blocked').length} |`,
 '| Registry Standard / Boss | 74 / 1 |',
 '',
 'All 66 printed panels were reviewed against the frozen literal observations. Each presently contains one printed rule paragraph. Panels are split into individually classified semantic rules with `sourceRuleIndex: 0`; new unreviewed panels fail generation. There is no default Special Rule → objective mapping.',
 '',
 '| Special-rule Quest / printed panel class (exclusive) | Count |','| --- | ---: |',
 ...['objective-affecting only','non-objective only','mixed','source-blocked'].map(k=>`| ${k} | ${special.filter(n=>kind(n)===k).length} |`),
 '',
 `Across all panels, ${special.filter(n=>n.specialRules.some(r=>r.affectsObjectiveCompletion)).length} Quests have objective-affecting rules (including mixed). Of ${rules.length} normalized semantic rules, ${rules.filter(r=>r.affectsObjectiveCompletion).length} affect objective qualification/completion/minimum eligibility and ${rules.filter(r=>!r.affectsObjectiveCompletion).length} do not. Source-blocked panels are counted separately above; their classified, unresolved leaves remain in the totals below.`,
 '',
 '| Semantic category | Rules |','| --- | ---: |',
 ...semanticCategories.map(k=>`| ${k} | ${rules.filter(r=>r.semanticCategory===k).length} |`),
 '',
 '## Objective and source architecture',
 '',
 '`objective.targetCount` and `xpUnit` express the printed XP qualification unit. Ordinary Quest XP remains normally 0–3 under S4:p14,p29; no XP rate becomes an invented mandatory quest threshold. `qualificationRules` and `completionRules` only reference explicitly bound rules. Non-objective rules always have `affectsObjectiveCompletion: false` and `objectiveBinding: null`.',
 '',
 'Fundraiser has an explicit minimum of one Lair; its 10 Gold reward and 20 Gold → 1 XP exchange are reward rules. Take ’Em Back has a one-Objective-Room minimum for the Trinket return XP exchange; its scope is exchange eligibility, not a new generic quest success condition. All other `minimumQuestGoal` values are null.',
 '',
 'Mixed panels retain separate room selection/setup, provision grants, monster policies, battle/initiative, exploration, loot, campaign and objective rules. In particular, Carrion Infestation separately binds the printed room-secured condition while preserving its battle-end rule; Ringleaders’ battle-end policy is not an additional kill-objective qualification. Tainted Trinkets keeps the Hamlet consequence separate from the in-room objective action. Lost and Found’s Valuable chest replacement is loot, not a room completion requirement.',
 '',
 'No Other Way retains the action, Torch, red Area, prohibited round 4 ignition and next-round burn resolution in objective rules. Refilling empty Stances at the end of the ignition round remains an independent monster-spawn rule. Null trigger means no additional timing was inferred. No once-per-round or pre-initiative timing was added.',
 '',
 'Dem Bones now uses `collect`, removing the old unsupported `collect-and-return` label because its reward says Bone collected. The repair also retains previously omitted set-aside clauses for Test the Waters / The Deep Ones and the chest-bearing room restriction for Take ’Em Back. Literal evidence was not changed.',
 '',
 'Each semantic leaf has card source identity, literal field, crop/hash and rulebook references where relevant in `leafProvenance`. Splitting a panel no longer turns the normalized array index into a printed source index. Objective bindings trace through the referenced rule. Boss objective context uses S4:p30,p35; generic XP evidence does not substitute for Boss semantics.',
 '',
 '## Before / after evidence',
 '',
 '| Quest | Before | After |','| --- | --- | --- |',
 '| Creeping Darkness | Stress panel → requiredConditions[0] | hero-stress; null binding; room count 2 is one XP unit |',
 '| The Threat is Real | Level restriction → requiredConditions[0] | monster-pool; no Level 1 in Lairs; null binding |',
 '| Patrol the Woods | Initiative panel → requiredConditions[0] | initiative at battle-start; null binding; room count 2 unchanged |',
 '| Dem Bones | Entire setup/collection/clear panel → requiredConditions[0] | Separate room setup; Green Area + 2 actions qualify bones; collection binds room completion |',
 '| Purify the Fountains | Potion grant, setup and purification all required | Setup/grant independent; 2 actions + Potion qualify purification; purified fountain binds room completion |',
 '| No Other Way | Room setup, ignition, reinforcement and clear policy all required | Setup/spawn independent; ignition/wait and burned-oak completion explicitly bound |',
 '| Fundraiser | Entire minimum/reward panel required | Only explicit 1 Lair minimum bound; Gold award and exchange unbound |',
 '| Face the Threat! | Boss setup and no-return both requiredConditions | Boss defeat objective; setup and campaign no-return rules unbound |',
 '',
 '## Full Quest audit ledger',
 '',
 'This ledger covers all 76 definitions, including ten without Special Rules. Category counts are semantic leaves, not extra cards or new registry definitions.',
 '',
 '| Cell | Printed name | Panel class | Objective-bound / total rules | Categories |','| --- | --- | --- | ---: | --- |',
 ...definitions.map(n=>`| ${cell(n)} | ${escape(n.printedName)} | ${n.specialRules.length?kind(n):'no special rules'} | ${n.specialRules.filter(r=>r.affectsObjectiveCompletion).length} / ${n.specialRules.length} | ${[...new Set(n.specialRules.map(r=>r.semanticCategory))].join(', ')||'—'} |`),
 '',
 '## Blockers and C1B migration list',
 '',
 '- `444-14 Rest in Rubble III`: the printed “causes Heroes to a tomb” is missing an action verb. Its `onClear` stays null and SOURCE_UNRESOLVED, with source-blocked provenance. No behavior is copied from Rest in Rubble I. It is excluded from the registry.',
 '- `CURRENT_CRITICAL_STONE_TIMING_MISMATCH`: Production `src/data/trinkets/verified-trinkets.ts` uses `before-attack-roll`, while S4:p26 explicitly allows declaring Critical Stone Crit +2 after seeing the roll. C1B must repair/migrate and test this timing. No Production Trinket change is made here.',
 '- `RUNTIME_PRIMITIVE_UNSUPPORTED` is not permission to integrate. C1B still needs deliberate runtime mappings, Community runtime profile, expansion filtering, rewards, persistence and Production/E2E checks.',
 '- Boss setup/no-return/rulebook mechanics remain separate from the defeat objective. Boss Association remains source-domain metadata. No Boss runtime work is part of this repair.',
 '',
 '## Verification and frozen baseline',
 '',
 '`npm run generate:complete-edition-c1ar` writes only Quest normalized definitions and registry data. `npm run verify:complete-edition-c1ar` audits all 76 definitions, explicit boolean/binding reciprocity, panel conservation, leaf provenance, XP units, minima, source-blocker conservation, deterministic generation, all 250 existing asset hashes, original C1A bundle invariants and exported immutable registries. QR-01…QR-08 cover the required counterexamples; 12 semantic mutations and 8 inherited C1A mutations must be rejected.',
 '',
 'The verifier compares all tracked changes to the exact C1A HEAD using an allowlist. C0 identities/inventory, literal observations/evidence, vendored assets, 49 physical / 48 registry / 1 blocked Trinkets, Production quest pool, QuestSelectPage, Campaign store/commands/save, Runtime Profile, Act IV and Final Encounter remain frozen. It additionally scans for Production imports of the Community Quest/Trinket registries. Existing user-owned untracked temporary files are not edited or removed.',
 '',
 'Historical C1A report, verification log and source-review lock are preserved. C1A-R has a separate authored semantic input lock, with the original Quest semantics hash checked against the C1A base. Use the C1A-R verifier for this branch: the historical C1A CLI intentionally retains its original review-lock contract and is not relabeled as current evidence.',
 '',
 'Validation commands: `npm run verify:complete-edition-c1ar`, `npm run typecheck`, `npm run build`. Results are recorded in `c1ar-verification.log`. This is source-domain interpretation and integrity verification against existing reviewed evidence, not a new independent visual/source audit. Independent audit remains required before C1B.',
 '',
 '**STOP: C1A-R complete; do not enter C1B.**',''
 ];
 return lines.join('\n');
}
if(process.argv[1]?.replaceAll('\\','/').endsWith('/c1ar-report.mjs'))writeFileSync('docs/reports/complete-edition/c1ar-quest-semantic-classification-repair-report.md',buildRepairReport(json(`${dataRoot}/quests/community-quest-normalized.json`).definitions,json(`${dataRoot}/quests/community-quest-source-evidence.json`).records));
