import { readFileSync, writeFileSync } from 'node:fs';
import { buildStandardQuestLiveRebaseline, assertStandardQuestLiveRebaseline } from '../../src/audit/standard-quest-live-rebaseline';
import { git, sha } from './c1c20-contract';
export const baselineHead = 'cef91c4cd31cf074e9d3b7db56098f473772f728';
export const baselineTree = '215bc0081a5369b7a68d9e645d28b42304d2e5cc';
export function artifacts() {
  const a = buildStandardQuestLiveRebaseline();
  assertStandardQuestLiveRebaseline(a);
  const history = JSON.parse(readFileSync('docs/data/complete-edition/c1c4-runtime-capability-matrix.json', 'utf8'));
  const meta = { phase: '11A.4-C1C-21', baselineHead, baselineTree, truthSource: 'LIVE_SOURCE_CAPABILITY_ADAPTER_PROOF_REGISTRY', schemaVersion: 1 };
  const freezePaths = git('ls-tree', '-r', '--name-only', baselineHead, '--', 'docs/data/complete-edition', 'docs/reports/complete-edition').split(/\r?\n/).filter(p => /\/c1c20-/.test(p));
  const freeze = Object.fromEntries(freezePaths.map(p => [p, sha(git('show', `${baselineHead}:${p}`).replace(/\r\n/g, '\n').trimEnd())]));
  const { roi, categories, decision, proofRegistry, ...matrix } = a;
  return {
    'c1c21-standard-quest-live-capability-matrix.json': { ...meta, ...matrix, coreTrinketFreeze: freeze, expectedReadyInvariant: { ids: ['community-quest-warrens-lvl1-explore-the-sewers','community-quest-warrens-lvl2-mapping-the-sewers','community-quest-warrens-lvl3-deep-in-the-warrens'].sort(), matches: a.readyIds.join('|') === ['community-quest-warrens-lvl1-explore-the-sewers','community-quest-warrens-lvl2-mapping-the-sewers','community-quest-warrens-lvl3-deep-in-the-warrens'].sort().join('|') } },
    'c1c21-standard-quest-runtime-roi-matrix.json': { ...meta, model: 'Primitive-only promotion retains live adapter/proof and rejects unbound semantic obligations; companions require all named missing primitives. No synthetic proofs or adapters.', rows: roi, semanticCategories: categories, reusedProofRegistry: proofRegistry },
    'c1c21-standard-quest-source-gap-register.json': { ...meta, quests: a.quests.filter(q => q.sourceGates.length).map(q => ({ definitionId: q.definitionId, literalComplete: q.literalComplete, sourceGates: q.sourceGates, rootBlockerFamilies: q.rootBlockerFamilies })) },
    'c1c21-rest-gated-quest-register.json': { ...meta, restAcceptanceErrors: a.restAcceptanceErrors, quests: a.quests.filter(q => q.sourceGates.includes('REST_INSUFFICIENT_RECOVERY_CAPACITY')).map(q => ({ definitionId: q.definitionId, firewoodTokens: q.firewoodTokens, restingPoints: q.restingPoints, restSemanticBlocker: 'insufficientRecoveryCapacity', wouldOtherwiseUseSimpleAdapter: q.wouldOtherwiseUseSimpleAdapter, proofAvailability: q.proofAvailability })) },
    'c1c21-trinket-dependent-quest-register.json': { ...meta, quests: a.quests.filter(q => q.requiredDeck).map(q => ({ definitionId: q.definitionId, name: q.name, requiredDeck: q.requiredDeck, deck: q.deck, readinessDependency: q.readinessDependency, readinessDependencyAudit: q.readinessDependencyAudit, randomDrawPolicy: q.randomDrawPolicy, sourceGates: q.sourceGates })), dependencyGraph: ['Core Trinket source gates -> complete Level 2/3 source deck -> source-complete random acquisition -> Quest Production Ready'], coreTrinketWorkstream: 'FROZEN_C1C20_15_OF_37' },
    'c1c21-next-quest-workstream-decision.json': { ...meta, ...decision },
    'c1c21-c1c4-delta.json': { ...meta, comparisonOnly: true, quests: a.quests.map(q => { const old = history.quests.find((r: {definitionId:string}) => r.definitionId === q.definitionId); return { definitionId: q.definitionId, c1c4ProductionStatus: old?.productionStatus ?? null, liveProductionStatus: q.productionStatus, newPrimitiveAvailable: q.requiredPrimitives.filter(p => a.implementedPrimitives.includes(p) && !history.implementedPrimitives.includes(p)), sourceGateChanged: old?.sourceSemanticComplete !== q.SOURCE_RULE_INTERPRETATION_COMPLETE, adapterChanged: old?.adapterComplete !== q.adapterComplete, proofChanged: old?.productionUiProofComplete !== q.productionUiProofComplete, reason: q.sourceGates.length ? q.sourceGates.join('; ') : q.downstreamRuntimeBlockers.join('; ') || 'Live adapter/proof/semantic truth retained' }; }) },
  };
}
export function report() {
  const a = buildStandardQuestLiveRebaseline();
  return `# C1C21 Standard Quest Live Rebaseline\n\nReady ${a.productionReadyCount}/75; not ready ${a.notReadyCount}. Source-gated ${a.sourceGateCount}; runtime/binding-only blocked ${a.runtimeOnlyBlockedCount}; proof-only ${a.proofOnlyBlockedCount}.\n\nReady IDs:\n\n${a.readyIds.map(id => '- ' + id).join('\n')}\n\nRest remains fail closed: insufficientRecoveryCapacity is SOURCE_UNRESOLVED. Live data has eight simple-adapter firewood cards (including Pork Chop), not the requested seven. All 70 firewood cards remain source-gated; Family and Tainted provide the remaining two source gates. The locked 75-card source set includes Face the Threat! with questType=boss; filtering questType=standard would incorrectly omit it.\n\nFamily: Level 2 4/11; Tainted: Level 3 4/12. Both require complete source decks. Tainted evaluator omits its Level 3 dependency; audit records MISSING_READINESS_DEPENDENCY and excludes promotion. Ready-subset substitution is forbidden.\n\nCore Trinket freeze: 15/37, levels 7/14, 4/11, 4/12. C1C20-CORE-TRINKET-TERMINAL-BLOCKER-CONSOLIDATION-ACCEPTED-SOURCE-GATED-15-OF-37.\n\nThe primitive frequency table is derived from live missing primitives plus semantic obligations, deduplicated per Quest. Unbound semantic categories are retained separately rather than guessed as implemented consumers. Condition, disease, exploration and Trinket consumers do not automatically establish Quest timing/target bindings.\n\nEvery primitive has zero immediate whole-Quest gain under current bindings, exact adapters and production proofs. This is a conservative primitive-only counterfactual, not a prediction that a complete family implementation with new adapters/proofs cannot promote cards. No family currently has a precisely specified, machine-bound positive promotion set; C1C22 must first audit Boss/Encounter inventory or close Quest consumer contracts. All 72 blocked cards have external source gates; most also have downstream runtime binding gaps. Their literal source rules are not thereby unknown.\n\nSelected family: ${a.decision.selectedFamily}. Expected immediate Ready gain: ${a.decision.expectedReadyGain}.\n\nExisting C1C1/C1C1R/C1C1R2/C1C2/C1C3 proofs are reused by ID and registry scope; primitive Rest E2E is not source-semantic closure. No gameplay changes or new E2E fixtures.\n\nC1C4 is comparison-only. Report does not assert full verification; see exact command logs and receipt in tmp/c1c21-verification.\n\nVerdict: C1C21-STANDARD-QUEST-LIVE-REBASELINE-ACCEPTED-READY-${a.productionReadyCount}-OF-75-NEXT-${a.decision.selectedFamily}\n`;
}
export function generate() {
  for (const [name, value] of Object.entries(artifacts())) writeFileSync(`docs/data/complete-edition/${name}`, JSON.stringify(value, null, 2) + '\n');
  writeFileSync('docs/reports/complete-edition/c1c21-standard-quest-live-rebaseline-report.md', report());
  console.log(report());
}
