import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { buildBossEncounterLiveInventory, assertBossEncounterLiveInventory } from '../../src/audit/boss-encounter-live-inventory';
export const baselineHead = '6d988d1f972388f4fa90986edf0cf7cf2ff2a4bb';
export const git = (...args: string[]) => execFileSync('git',args,{encoding:'utf8',maxBuffer:128*1024*1024}).trim();
const hash = (p: string) => createHash('sha256').update(readFileSync(p)).digest('hex');
export function artifacts() {
  const a = buildBossEncounterLiveInventory(); assertBossEncounterLiveInventory(a);
  const paths = ['docs/data/complete-edition/complete-edition-raw-inventory.json','src/data/community-reference/quests/data.json','docs/data/darkest-dungeon/community-reference/antha-complete-edition/normalized-requirements.json',
    ...git('ls-tree','-r','--name-only',baselineHead,'--','docs/data/complete-edition','docs/reports/complete-edition').split(/\r?\n/).filter(p => /\/c1c(?:20|21)-/.test(p))];
  const meta = { schemaVersion: 1, phase: '11A.4-C1C-22', baselineHead: git('rev-parse',baselineHead), baselineTree: git('rev-parse',baselineHead+'^{tree}'), inputSha256: Object.fromEntries(paths.map(p => [p,hash(p)])) };
  return {
    'c1c22-boss-encounter-live-inventory.json': {...meta,...a},
    'c1c22-boss-encounter-source-gap-register.json': {...meta,cards:a.cards.filter(c => c.requiredSourceExtraction.length || c.questSourceGates.length)},
    'c1c22-boss-encounter-opportunity-matrix.json': {...meta,families:a.families,existingAct4Runtime:a.existingAct4Runtime},
    'c1c22-next-workstream-decision.json': {...meta,...a.nextDecision},
    'c1c22-hamlet-event-source-intake-register.json': {...meta,scope:'Extraction candidates only; not normalized gameplay definitions',cards:a.cards.filter(c => c.category === 'Encounter / Event Content'),requiredFields:['name','front and back literals','target','timing','choices','effects','deck copies','discard/reshuffle lifecycle','source references','asset SHA-256'],acceptance:'No runtime implementation selection until source semantics and whole-content Ready gain are established'},
  };
}
export function report() {
  const a=buildBossEncounterLiveInventory();
  return `# C1C22 Boss / Encounter Live Inventory\n\nThis is an inventory/source-contract audit; no gameplay implementation or new Ready promotion.\n\n| Category | Card objects | Physical cards | Unbound printed definitions | Live Quest bound | Act4 references |\n|---|---:|---:|---:|---:|---:|\n${a.categories.map(c=>`| ${c.category} | ${c.cardObjectCount} | ${c.physicalCardCount} | ${c.printedDefinitionNotBoundCount} | ${c.liveQuestBoundCount} | ${c.act4ReferenceCount} |`).join('\n')}\n\nThe locked census contains ${a.cardObjectCount} card objects. ${a.newContentSourceBlockedCount} ordinary Boss/Event cards lack source definitions; ${a.existingQuestSourceGatedCount} Boss Quest is already source-bound but blocked by Rest; ${a.existingAct4ReferenceCount} Guardian/Final cards are references into the existing Act4 workstream and are not reclassified as new Ready cards.\n\nFace the Threat! is present in the 75-card C1C21 census and current Quest source data. Its historical raw-inventory not-extracted tag is superseded by the live source binding; its Firewood 1 / Resting Points 12 retains the unresolved Rest gate. Do not double-count it as new content.\n\nZero Threat Cards rows is a classification limitation, not absence of printed threat cards. The 231 ordinary Boss cards have unclassified battle/threat/ability subtypes. Visual identities and container names are not confirmed semantic definitions. Requirement asset citations may reference supporting components; the audit exposes references without treating them as runtime/proof coverage. Normalized partial labels do not supersede later independent Act4 acceptance.\n\nImmediate implementation target: none. Runtime-only whole-content Ready gain: 0. Select the 16-card Hamlet Event deck for bounded source intake because it is smaller and has a single explicit source container. This is an extraction priority, not a claim that Events have the largest gameplay ROI. Mock Hamlet events and prototype bosses are not source evidence.\n\nNext action: C1C23 Hamlet Event printed-definition intake. The register supplies exact TTS paths, GUIDs, card/deck/cell IDs, grid dimensions, front/back URLs and required semantic fields. Acquire and hash original sheets; crop and independently transcribe all front/back rules; close timing, choices and deck lifecycle; rerun ROI before gameplay.\n\nC1C20 Core Trinket and C1C21 Quest freezes remain intact (15/37 and 3/75). C1C21 full verification was not accepted: C1C13/12/11 exhausted their permitted reload retry, and C1C3 failed selecting gated Quest cards. These are retained upstream failures, not silently cleared by this audit.\n\nValidation of this audit is recorded separately; no blanket historical E2E success is claimed.\n`;
}
export function generate(){for(const[name,value]of Object.entries(artifacts()))writeFileSync('docs/data/complete-edition/'+name,JSON.stringify(value,null,2)+'\n');writeFileSync('docs/reports/complete-edition/c1c22-boss-encounter-live-inventory-report.md',report());console.log(report());}
