/** Offline visual transcription of locked publisher card faces, reviewed 2026-10-04.
 * Tuple compression is authoring-only; generated production data has named fields.
 * Effect strings describe printed glyphs, never an executable effect contract.
 */
export type ReviewedAction = [name: string, range: number | null, targets: number | 'ALL_HEROES' | null,
  priority: string, attack: [accuracy: number, damage: number, crit: number, critDamage: number] | number | null,
  effects: string[]];
export interface ReviewedPrint {
  set: string; page: number; end: number; largePages?: number[]; id?: string;
  name: string; level: number; life: number; speed: number | null; dodge: number;
  resistances: string[]; immunities: string[]; protection?: boolean;
  actions: ReviewedAction[]; stances: [string, string, string, string];
}
// a/d/r/s = inheritance. '-' = printed crossed-out stance. Otherwise skill[:d10 range].
const all = (table: string): ReviewedPrint['stances'] => ['s','s','s',table];
export const reviewedPrints: ReviewedPrint[] = [
  {set:'COREBOX',page:63,end:65,name:'Ascended Brawler',level:3,life:22,speed:2,dodge:3,resistances:['push-pull'],immunities:[],
    actions:[['Rend for the New God',1,1,'Closest',[10,6,1,10],['Self: Pull 1','Target: [bleed] 2 3t; [debuff] 1t; +3 damage vs [marked]']],['Stumbling Scratch',1,1,'Furthest',[7,6,0,10],['Self: Pull 1']]],stances:['d','1','-','2']},
  {set:'COREBOX',page:66,end:68,name:'Ascended Witch',level:3,life:18,speed:2,dodge:4,resistances:['debuff'],immunities:[],
    actions:[["Fate’s Reveal",2,1,'Furthest',[10,2,0,3],['Target: [stress] +2; [light] -1; [marked] 2t']],["Fate’s Push",1,1,'Closest',[10,2,1,3],['Target: Push 2; [stress] +1']],["Fate’s Pull",2,1,'Furthest',[10,2,1,3],['Target: Pull 2; [stress] +1']]],stances:all('1:1-3,2:4-7,3:8-10')},
  {set:'COREBOX',page:69,end:71,name:'Rapturous Cultist',level:3,life:14,speed:3,dodge:0,resistances:[],immunities:[],
    actions:[['Flesh Wall',null,null,'Self',null,['Self: [guard] 1t']],['Flesh to Flesh',0,1,'Most Wounded Monster',null,['Target: [heal] 9']]],stances:all('1:1-6,2:7-10')},
  {set:'COREBOX',page:72,end:74,name:'Cultist Priest',level:3,life:26,speed:2,dodge:3,resistances:['bleed'],immunities:[],
    actions:[['Death Lash',1,2,'Crowded',[11,6,1,8],['Target: [debuff] 1t; [stress] +1']],['The Finger',2,1,'Furthest',[11,11,2,15],['Target: [bleed] 3 3t; [stress] +2; +5 damage vs [marked]']]],stances:all('1:1-6,2:7-10')},
  {set:'COREBOX',page:75,end:77,name:'Malignant Growth',level:3,life:28,speed:1,dodge:2,resistances:['bleed'],immunities:[],
    actions:[['Maul the Flesh',1,1,'Closest',[10,11,1,16],['Target: [bleed] 2 3t']],['Daze the Mind',1,1,'Furthest',[11,6,1,10],['Target: [stun] 2t']]],stances:all('1:1-5,2:6-10')},
  {set:'COREBOX',page:78,end:79,name:'Flesh Hound',level:3,life:23,speed:3,dodge:3,resistances:['push-pull'],immunities:[],
    actions:[['Gnash',1,1,'Closest',[10,9,1,14],['Target: [stress] +1']],['Nibble',2,1,'Closest',[9,2,0,4],['Self: Pull 2']],['Fetch',2,1,'Furthest',[11,7,1,10],['Target: [stun] 1t; Pull 2']]],stances:['r','r','1:1-5,3:6-10','2']},
  {set:'COREBOX',page:80,end:82,name:'Polyp',level:3,life:17,speed:3,dodge:3,resistances:['blight'],immunities:[],
    actions:[['Venomous Phlegm',2,1,'Furthest',[10,6,1,10],['Target: [blight] 3 3t; [marked] 2t']],['Violent Hack',1,1,'Closest',[8,2,0,4],['Self: Push 2']],['Unholy Rally',1,1,'Closest',[11,6,1,10],['Target: Push 2']]],stances:['2','s','s','1:1-5,3:6-10']},
  {set:'COREBOX',page:83,end:85,name:'Antibody',level:3,life:28,speed:2,dodge:3,resistances:['stun','bleed'],immunities:[],
    actions:[['Stunning Secretion',1,1,'Closest',[11,12,0,18],['Target: [stun] 1t']]],stances:all('1')},
  {set:'COREBOX',page:86,end:88,name:'Defensive Growth',level:3,life:17,speed:2,dodge:2,resistances:['bleed','push-pull'],immunities:[],
    actions:[['Bolster',1,1,'Closest Monster',null,['Target: [buff] 3t']],['Ritualic Restoration',1,1,'Closest Monster',null,['Self: Push 2','Target: [heal] 17']],['Unbearable Tremors',2,4,'Crowded',12,['Target: [stress] +2']]],stances:all('1:1-3,2:4-6,3:7-10')},
  {set:'CRIMSONCourt',page:1,end:3,name:'Manservant',level:1,life:7,speed:3,dodge:2,resistances:['stun','blight'],immunities:[],
    actions:[['Enraging Slight',2,1,'Furthest',[9,2,0,4],['Target: [stress] +1; [marked] 2t; Pull 2']],['The Thirst',1,1,'Closest',[10,3,0,6],['Self: [heal] 4','Target: [debuff] 1t; [stress] +2']],['Infallible Servitude',null,null,'Self',null,['Self: [guard] 1t; [protection] 1t; [buff] 2t']]],stances:all('1:1-4,2:5-8,3:9-10')},
  {set:'CRIMSONCourt',page:4,end:6,name:'Esquire',level:1,life:11,speed:1,dodge:0,resistances:['stun','blight'],immunities:[],
    actions:[['Rib Cracker',1,1,'Furthest',[9,4,1,6],['Self: Push 2','Target: [debuff] 1t; Push 1']],['The Thirst',1,1,'Closest',[10,3,0,6],['Self: [heal] 4; [debuff] 1t; Pull 1','Target: [stress] +1']],['Skewering Repartee',1,4,'Crowded',[9,6,0,9],['Self: Pull 1','Target: [bleed] 2 2t']]],stances:['d','1:1-5,2:6-10','-','3:1-5,2:6-10']},
  {set:'CRIMSONCourt',page:7,end:9,name:'Supplicant',level:1,life:9,speed:1,dodge:0,resistances:[],immunities:['stun'],
    actions:[['Gather the Blood',1,1,'Closest',[8,4,0,6],['Self: Pull 1','Target: [printed-red-card-glyph]']],['Predigestion',2,1,'Furthest',[8,3,1,5],['Self: Pull 2','Target: [blight] 2 2t; [debuff] 1t']]],stances:['d','1:1-8,2:9-10','-','2']},
  {set:'CRIMSONCourt',page:10,end:12,name:'Gatekeeper',level:1,life:8,speed:2,dodge:2,resistances:['blight'],immunities:[],
    actions:[['Enraging Slight',2,1,'Furthest',[9,2,1,4],['Target: [stress] +1; [marked] 2t; Pull 2']],['Elusive Exit',2,4,'Crowded',[12,2,0,3],['Self: 8 [wound]','Target: [stress] +3']]],stances:all('1:1-8,2:9-10')},
  {set:'CRIMSONCourt',page:13,end:15,name:'Sycophant',level:1,life:8,speed:3,dodge:2,resistances:['blight'],immunities:[],
    actions:[['Maddening Whine',2,1,'Furthest',[9,2,1,3],['Self: Push 2','Target: [stress] +1']],['The Thirst',0,1,'Closest',[10,3,1,5],['Self: [buff] 2t','Target: [stress] +1; [printed-red-card-glyph]']]],stances:all('1:1-6,2:7-10')},
  {set:'CRIMSONCourt',page:16,end:18,name:'Courtesan',level:2,life:14,speed:2,dodge:2,resistances:['stun','blight','debuff'],immunities:[],
    actions:[['Careless Whispers',2,4,'Crowded',[10,2,0,4],['Self: Pull 2','Target: [debuff] 1t; [stress] +1']],['Mind Your Manners',1,1,'Closest',[10,5,1,7],['Target: [marked] 2t']],['The Thirst',0,1,'Closest',[10,4,1,6],['Target: [stress] +1; [printed-red-card-glyph]']]],stances:['2:1-5,3:6-10','s','s','1:1-4,2:5-7,3:8-10']},
  {set:'CRIMSONCourt',page:19,end:21,name:'Chevalier',level:2,life:19,speed:1,dodge:1,resistances:['blight'],immunities:['push-pull'],
    actions:[['Buried Blast',2,2,'Crowded',[9,6,0,9],['Target: [stun] 1t; [debuff] 1t']],['Subterranean Skewer',1,1,'Closest',[9,9,1,12],['Self: Push 1','Target: [bleed] 2 3t; [debuff] 1t']]],stances:['2','s','s','1:1-5,2:6-10']},
  {set:'CRIMSONCourt',page:22,end:22,largePages:[1],name:'Crocodillian',level:3,life:66,speed:2,dodge:1,resistances:['stun'],immunities:['blight'],
    actions:[['Swarming Corruption',1,4,'Crowded',[9,4,0,6],['Target: [debuff] 1t; [stress] +1']],['Teeth Rake',0,1,'Closest',[10,6,1,9],['Target: [bleed] 2 3t; [stress] +1; Push 2']],['Apex Predator',2,1,'Furthest',[10,11,1,16],['Self: Pull 2']]],stances:['2','1:1-5,2:6-10','-','1:1-8,3:9-10']},
  {set:'WARRENS',page:1,end:3,name:'Swine Chopper',level:1,life:14,speed:1,dodge:0,resistances:['blight','push-pull'],immunities:[],
    actions:[['Butcher Cut',1,1,'Closest',[9,5,1,8],['Target: [bleed] 2 2t']],['Ball and Chain',2,1,'Furthest',[9,3,1,5],['Target: [stun] 1t; Push 1']]],stances:['d','1:1-8,2:9-10','-','2']},
  {set:'WARRENS',page:4,end:6,name:'Swine Slasher',level:1,life:6,speed:2,dodge:1,resistances:['bleed'],immunities:[],
    actions:[['Hook Where It Hurts',0,1,'Closest',[9,5,2,8],['Self: Push 1']]],stances:all('1')},
  {set:'WARRENS',page:7,end:9,name:'Swine Wretch',level:1,life:9,speed:3,dodge:1,resistances:['blight'],immunities:[],
    actions:[['Vomit',2,1,'Furthest',[9,1,2,2],['Target: [stress] +1; [disease]']]],stances:all('1')},
  {set:'WARRENS',page:10,end:12,name:'Swine Drummer',level:1,life:10,speed:2,dodge:0,resistances:['blight'],immunities:[],
    actions:[['Drum of Doom',1,4,'Crowded',[9,1,1,2],['Target: [stress] +1']],['Drum of Debilitation',2,1,'Furthest',[9,1,1,2],['Target: [debuff] 2t; [marked] 2t']]],stances:all('1:1-5,2:6-10')},
  {set:'WARRENS',page:13,end:15,name:'Carrion Eater',level:1,life:6,speed:2,dodge:0,resistances:['bleed'],immunities:['blight'],
    actions:[['Munch',1,1,'Closest',[8,3,2,6],['Target: +3 damage vs [marked]; [blight] 1 3t']]],stances:all('1')},
  {set:'WARRENS',page:16,end:16,largePages:[8],name:'Large Carrion Eater',level:2,life:33,speed:1,dodge:1,resistances:['bleed','push-pull'],immunities:['blight'],
    actions:[['Weaken Prey',1,1,'Closest',[10,4,1,6],['Target: [debuff] 2t; [marked] 2t']],['Tentacle Devour',1,1,'Closest',[10,10,2,16],['Target: +5 damage vs [marked]; [debuff] 1t']]],stances:all('1:1-5,2:6-10')},
  {set:'WARRENS',page:17,end:17,largePages:[1],name:'Swinetaur',level:2,life:40,speed:1,dodge:1,resistances:['stun'],immunities:['push-pull'],
    actions:[['Pig Spear',1,4,'Crowded',[9,6,1,11],['Self: Pull 1']],['Boar Rush',2,1,'Furthest',[9,11,2,17],['Self: Pull 2','Target: [stun] 1t']],['Trot Retreat',1,1,'Closest',[8,7,1,10],['Self: Push 2','Target: [stun] 1t']]],stances:['d','3','s','1:1-5,2:6-10']},
  {set:'WARRENS',page:18,end:19,name:'Swine Skiver',level:3,life:33,speed:3,dodge:3,resistances:['stun','blight'],immunities:[],
    actions:[['Spit to Roast',2,1,'Closest',[11,14,2,19],['Self: Pull 1','Target: [stun] 1t; Push 2']],['Cripple Them',2,3,'Crowded',[10,9,1,14],['Target: [blight] 2 3t; [debuff] 1t']],['Goring Flight',0,1,'Closest',[10,5,1,8],['Self: Push 3']]],stances:['3','1:1-4,2:5-8,3:9-10','-','1:1-5,2:6-10']},
  {set:'COVE',page:1,end:3,name:'Pelagic Shaman',level:1,life:8,speed:3,dodge:1,resistances:['bleed'],immunities:[],
    actions:[['Stress Wave',2,2,'Crowded',[9,1,0,2],['Self: Push 1','Target: [stress] +1']],['Call of the Deep',1,1,'Most Wounded Monster',null,['Target: [heal] 9; [buff] 2t']],['Ceremonial Cut',0,1,'Closest',[7,3,1,6],[]]],stances:['3','s','s','1:1-5,2:6-10']},
  {set:'COVE',page:4,end:6,name:'Drowned Thrall',level:1,life:10,speed:1,dodge:0,resistances:['stun'],immunities:[],
    actions:[['Gargling Grab',0,1,'Closest',[7,1,0,10],['Target: [stress] +1']],['The Revenge',1,4,'Crowded',[20,9,1,14],['Self: Pull 1; after resolving the attack: 10 [wound]','Target: [stress] +1']]],stances:all('1:1-9,2:10-10')},
  {set:'COVE',page:7,end:9,name:'Pelagic Grouper',level:1,life:9,speed:2,dodge:1,resistances:['bleed'],immunities:[],
    actions:[['Seaward Slash',0,1,'Closest',[8,7,0,11],[]],['Spearfishing',2,1,'Furthest',[8,5,1,8],[]]],stances:['d','1','-','2']},
  {set:'COVE',page:10,end:12,name:'Deep Stinger',level:1,life:7,speed:2,dodge:1,resistances:['stun','bleed'],immunities:[],
    actions:[['Shocker',1,1,'Furthest',[10,1,1,2],['Target: [stun] 1t; [debuff] 1t; [disease]']],['Salty Gouge',0,1,'Closest',[10,3,1,6],['Target: [bleed] 2 2t; [debuff] 2t; [disease]']]],stances:all('1:1-5,2:6-10')},
  {set:'COVE',page:13,end:15,name:'Sea Maggot',level:1,life:4,speed:1,dodge:0,resistances:['stun'],immunities:[],
    actions:[['Brine',1,1,'Closest',[7,3,0,5],['Target: [debuff] 2t; [disease]']]],stances:all('1')},
  {set:'COVE',page:16,end:17,name:'Pelagic Guardian',level:1,life:16,speed:1,dodge:0,resistances:['bleed','push-pull'],immunities:[],protection:true,
    actions:[['Octocestus',1,1,'Closest',[8,4,1,7],['Target: [bleed] 2 2t']],['Barnacle Barrier',null,null,'Self',null,['Self: [guard] 1t; [buff] 2t']]],stances:all('1:1-8,2:9-10')},
  {set:'COVE',page:18,end:19,largePages:[1,2],name:'Uca Major',level:2,life:39,speed:1,dodge:1,resistances:['stun','bleed','push-pull'],immunities:[],protection:true,
    actions:[['Arterial Pinch',1,1,'Closest',[9,2,1,4],['Target: [bleed] 3 3t; [debuff] 2t']],['Tidal Slam',1,1,'Closest',[9,7,1,11],['Target: [stun] 1t; Push 3']]],stances:['d','1:1-5,2:6-10','-','1']},
  {set:'COVE',page:20,end:22,name:'Squiffy Ghast',level:3,life:33,speed:3,dodge:4,resistances:['bleed'],immunities:['stun'],
    actions:[['Maddening Shanty',2,1,'Furthest',[9,2,0,4],['Self: Pull 2','Target: [debuff] 2t; [stress] +2']],['Offkilter Jig',2,2,'Crowded',[9,0,0,1],['Self: Push 2','Target: [stress] +1; [printed-red-card-glyph]']]],stances:['r','r','1:1-3,2:4-10','1']},
  {set:'WEALD',page:1,end:3,name:'Ectoplasm',level:1,life:6,speed:1,dodge:0,resistances:['blight'],immunities:[],
    actions:[['Slime',1,1,'Closest',[9,4,1,7],[]],['Cytokinesis',1,1,'Closest',[9,1,1,2],['Target: [summon] 1 Ectoplasm']],['Ectoplasmic Profusion',1,4,'Crowded',[9,1,1,2],['Target: [summon] 1 Large Ectoplasm; [stress] +1']]],stances:all('1:1-5,2:6-8,3:9-10')},
  {set:'WEALD',page:4,end:5,largePages:[1,2],name:'Large Ectoplasm',level:1,life:22,speed:1,dodge:0,resistances:['stun'],immunities:[],
    actions:[['Big Slime',1,1,'Closest',[9,6,1,9],[]],['Slime Smack',1,3,'Crowded',[9,3,3,6],['Target: [stun] 1t']],['Cytokinesis',1,1,'Closest',[9,3,1,6],['Target: [summon] 1 Large Ectoplasm']]],stances:all('1:1-4,2:5-8,3:9-10')},
  {set:'WEALD',page:6,end:8,name:'Rabid Gnasher',level:1,life:7,speed:3,dodge:2,resistances:['stun'],immunities:[],
    actions:[['Rabid Rush',2,1,'Furthest',[9,2,2,4],['Self: Pull 2','Target: [bleed] 1 3t; [disease]']]],stances:all('1')},
  {set:'WEALD',page:9,end:11,name:'Fungal Scratcher',level:1,life:14,speed:1,dodge:0,resistances:['blight'],immunities:[],
    actions:[['Groping Swipe',1,1,'Closest',[8,4,1,7],[]],['Rend the Marked',1,1,'Marked -> Closest',[9,4,1,6],['Target: +3 damage vs [marked]']],['Harmless Swipe',2,1,'Furthest',[5,3,0,6],['Self: Pull 1']]],stances:['d','1:1-5,2:6-10','-','3']},
  {set:'WEALD',page:12,end:14,name:'Fungal Artillery',level:1,life:9,speed:1,dodge:1,resistances:['blight'],immunities:[],
    actions:[['Mark Prey',2,1,'Closest',[10,1,1,2],['Target: [marked] 2t; [debuff] 2t']],['Rain of Blight',2,2,'Crowded',[10,1,1,2],['Target: [blight] 2 2t; [disease]']],['Escape Cloud',1,1,'Closest',[10,1,1,2],['Self: Push 2','Target: [blight] 1 3t']]],stances:['d','3','-','1:1-5,2:6-10']},
  {set:'WEALD',page:15,end:16,name:'Crone',level:2,life:12,speed:3,dodge:3,resistances:['blight','debuff'],immunities:[],
    actions:[['Curse of Vulnerability',2,2,'Crowded',[9,2,1,4],['Target: [marked] 2t; [debuff] 2t']],['Fetid Censer',0,1,'Closest',[9,3,1,6],['Target: [blight] 3 2t; [stress] +1; [disease]']],['Embrace the Dark',2,2,'Crowded',null,['Target: [stress] +1; [light] -1']]],stances:['d','1:1-2,2:3-8,3:9-10','-','1:1-5,3:6-10']},
  {set:'WEALD',page:17,end:17,largePages:[3],name:'Unclean Giant',level:2,life:60,speed:1,dodge:1,resistances:['stun','blight','push-pull'],immunities:[],
    actions:[['Treebranch Smackdown',1,1,'Closest',[9,16,1,24],['Target: Push 1']],['Confusion Spores',2,4,'Crowded',[9,2,1,4],['Target: [debuff] 2t']],['Poison Spores',2,1,'Furthest',[9,2,0,4],['Target: [blight] 2 3t']]],stances:all('1:1-2,2:3-6,3:7-10')},
  {set:'WEALD',page:18,end:19,name:'Hateful Virago',level:3,life:39,speed:3,dodge:4,resistances:['blight','debuff'],immunities:['stun'],
    actions:[['Ruinous Hex',1,2,'Crowded',[10,6,0,9],['Target: [marked] 2t; [debuff] 2t']],['Putrefying Breath',2,1,'Closest',[10,9,1,14],['Target: [blight] 3 3t; Push 1']]],stances:all('1:1-5,2:6-10')},
  {set:'COM',page:1,end:2,name:'Farmhand',level:1,life:6,speed:2,dodge:1,resistances:['blight'],immunities:[],
    actions:[['Sow the Seeds',2,1,'Furthest',[9,1,0,2],['Target: [blight] 2 2t; [stress] +1']],['Pause From Labor',null,null,'Self',null,['Self: [heal] 4; [buff] 2t']],['Ceaseless Labor',0,2,'Crowded',[8,3,1,5],['Target: +2 damage vs [marked]']]],stances:['d','3:1-7,2:8-10','-','1']},
  {set:'COM',page:3,end:4,name:'Foreman',level:1,life:10,speed:2,dodge:0,resistances:['blight'],immunities:[],
    actions:[['Stir the Rabble',1,1,'Closest Monster',null,['Self: [guard] 2t','Target: [buff] 2t']],['No Trespassers',1,1,'Closest',[9,5,1,9],['Self: [riposte] 1t','Target: [debuff] 2t; [blight] 2 2t; [marked] 2t']]],stances:all('2:1-7,1:8-10')},
  {set:'COM',page:5,end:6,name:'Scarecrow',level:1,life:6,speed:1,dodge:2,resistances:['stun','bleed'],immunities:[],
    actions:[['Haunting Revelation',2,1,'Furthest',[9,1,0,3],['Target: [stress] +1']],['Flail the Crops',1,1,'Closest',[9,3,0,7],['Target: [blight] 2 2t']]],stances:['d','2','-','1']},
  {set:'COM',page:7,end:7,largePages:[1],name:'Plow Horse',level:1,life:8,speed:3,dodge:1,resistances:['stun','push-pull'],immunities:[],protection:true,
    actions:[['Trample',2,4,'Crowded',[9,2,0,4],['Self: Pull 2','Target: [stun] 1t']],['Bestial Scream',2,4,'Crowded',null,['Self: [buff] 2t','Target: [stress] +2']],['Rearing Strike',1,1,'Closest',[9,3,1,7],['Target: [stun] 1t; Push 1']]],stances:['d','2:1-3,3:4-10','-','2:1-3,1:4-10']},
  {set:'COM',page:8,end:8,name:'Crystalline Aberration',level:1,life:3,speed:null,dodge:0,resistances:[],immunities:['stun','bleed','blight','debuff','push-pull'],
    actions:[['Unstable Resonance',null,'ALL_HEROES','All Heroes',[10,5,1,10],['Self: After the action is finished: 10 [wound]','Target: [blight] 2 2t']],['Explosive Undoing',null,'ALL_HEROES','All Heroes',[12,2,1,4],['Self: After the action is finished: 10 [wound]','Target: [stress] +2']]],stances:all('1:1-5,2:6-10')},
  {set:'COM',page:9,end:10,name:'Sleeper’s Herald',level:1,life:4,speed:3,dodge:1,resistances:['stun','bleed','blight'],immunities:[],protection:true,
    actions:[['Reality Bend',2,1,'Furthest',[10,1,0,2],['Target: [debuff] 2t; [stress] +1']]],stances:all('1')},
  {set:'COM',page:11,end:12,name:'Farmhand',level:2,life:9,speed:2,dodge:2,resistances:['bleed','blight'],immunities:[],
    actions:[['Sow the Seeds',2,1,'Furthest',[10,2,1,4],['Target: [blight] 3 3t; [stress] +1']],['Pause From Labor',null,null,'Self',null,['Self: [heal] 8; [buff] 3t']],['Ceaseless Labor',0,2,'Crowded',[9,5,1,8],['Target: +5 damage vs [marked]']]],stances:['d','3:1-7,2:8-10','-','1']},
  {set:'COM',page:13,end:14,name:'Foreman',level:2,life:16,speed:2,dodge:1,resistances:['stun','blight','push-pull'],immunities:[],
    actions:[['Stir the Rabble',1,1,'Closest Monster',null,['Self: [guard] 3t','Target: [buff] 3t']],['No Trespassers',1,1,'Closest',[10,8,2,13],['Self: [riposte] 2t','Target: [debuff] 2t; [blight] 2 3t; [marked] 2t']]],stances:all('2:1-7,1:8-10')},
  {set:'COM',page:15,end:16,name:'Scarecrow',level:2,life:9,speed:1,dodge:3,resistances:['stun'],immunities:['bleed'],
    actions:[['Haunting Revelation',1,1,'Furthest',[10,2,1,5],['Target: [stress] +2']],['Flail the Crops',1,1,'Closest',[10,6,0,14],['Target: [blight] 2 3t']]],stances:['d','2','-','1']},
  {set:'COM',page:17,end:17,largePages:[2],name:'Plow Horse',level:2,life:12,speed:3,dodge:1,resistances:['stun','push-pull'],immunities:[],protection:true,
    actions:[['Trample',2,4,'Crowded',[10,3,0,6],['Self: Pull 2','Target: [stun] 1t']],['Bestial Scream',2,4,'Crowded',null,['Self: [buff] 4t','Target: [stress] +2; [debuff] 3t']],['Rearing Strike',1,1,'Closest',[9,6,2,14],['Target: [stun] 1t; [blight] 1 3t; Push 1']]],stances:['d','2:1-3,3:4-10','-','2:1-3,1:4-10']},
  {set:'COM',page:18,end:18,name:'Crystalline Aberration',level:2,life:6,speed:null,dodge:0,resistances:[],immunities:['stun','bleed','blight','debuff','push-pull'],
    actions:[['Unstable Resonance',null,'ALL_HEROES','All Heroes',[12,8,1,12],['Self: After the action is finished: 10 [wound]','Target: [stun] 1t; [blight] 2 2t']],['Explosive Undoing',null,'ALL_HEROES','All Heroes',[12,3,1,5],['Self: After the action is finished: 10 [wound]','Target: [stun] 1t; [debuff] 2t; [stress] +3']]],stances:all('1:1-5,2:6-10')},
  {set:'COM',page:19,end:20,name:'Sleeper’s Herald',level:2,life:6,speed:3,dodge:2,resistances:['stun','bleed','blight'],immunities:[],protection:true,
    actions:[['Reality Bend',2,1,'Furthest',[12,2,1,3],['Target: [debuff] 3t; [stress] +2']]],stances:all('1')},
];
