import { execFileSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { COMMUNITY_DATASET } from '../../src/data/darkest-dungeon/community-reference/data';
import { deriveCommunityMetrics, validateCommunityReference, validateRegenerationParity } from '../../src/data/darkest-dungeon/community-reference/validate';

const inputAt = process.argv.indexOf('--input');
if (inputAt < 0 || !process.argv[inputAt + 1]) throw new Error('Usage: npm run verify:community-reference-binding -- --input <Astra intake package>');
const input = resolve(process.argv[inputAt + 1]);
const root = resolve('docs/data/darkest-dungeon/community-reference/antha-complete-edition');
const artifacts = ['normalized-requirements.json','source-reference-index.json','source-binding-manifest.json'];
const sha = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');
const inputHash = sha(input); const temp = mkdtempSync(join(tmpdir(), 'dd-community-binding-'));
const commands: Record<string, { exitCode: number }> = {};
const run = (name: string, executable: string, args: string[]) => { try { execFileSync(executable, args, { cwd: process.cwd(), stdio: 'inherit' }); commands[name]={exitCode:0}; } catch { commands[name]={exitCode:1}; } };
run('regeneration', process.execPath, ['scripts/audit/generate-community-reference-normalized.mjs','--input',input,'--out',temp]);
const committedArtifactHashes = Object.fromEntries(artifacts.map(name => [name, sha(join(root,name))]));
const regeneratedArtifactHashes = Object.fromEntries(artifacts.map(name => [name, commands.regeneration.exitCode === 0 ? sha(join(temp,name)) : 'generation-failed']));
const regenerationParity = validateRegenerationParity(committedArtifactHashes, regeneratedArtifactHashes).length === 0;
run('adversarialTests', process.execPath, ['node_modules/vitest/vitest.mjs','run','src/data/darkest-dungeon/community-reference/validate.test.ts']);
run('typecheck', process.execPath, ['node_modules/typescript/bin/tsc','--noEmit']);
const metrics = deriveCommunityMetrics(COMMUNITY_DATASET); const validationErrors = validateCommunityReference(COMMUNITY_DATASET);
const blockedFields = ['tierB-templars-room.pitExitRule','tierB-absolute-nothingness.stance','tierB-gestating-heart.lethalWoundTimingRuling','tierB-come-unto-your-maker.definition','tierB-darkest-dungeon-monster-deck.drawPolicy'];
const official = JSON.parse(readFileSync(resolve('docs/data/core-campaign/verification-results.json'),'utf8'));
const officialGate = { runId:official.runId, measuredAt:official.measuredAt, phase11A3Status:official.phase11A3Status, requiredMissing:official.sourceReadinessRequiredMissingCount, optionalMissing:official.sourceReadinessOptionalMissingCount, openP0:official.openP0, openP1:official.openP1, onlyOpenP0:official.releaseGateSummary?.onlyOpenP0, formalMatrixRun:official.releaseGateSummary?.officialGuardianMatrix?.combinationsRun, formalMatrixExpected:9, canCloseP0_002:official.canCloseP0_002, canEnterPhase11B:official.canEnterPhase11B };
const errors = [...validationErrors]; if (!regenerationParity) errors.push('regeneration parity'); if (Object.values(commands).some(x => x.exitCode !== 0)) errors.push('verification command'); if (inputHash !== COMMUNITY_DATASET.corpus.sourcePackageSha256) errors.push('input hash'); if (JSON.stringify([officialGate.phase11A3Status,officialGate.requiredMissing,officialGate.optionalMissing,officialGate.openP0,officialGate.openP1,officialGate.onlyOpenP0,officialGate.formalMatrixRun,officialGate.canCloseP0_002,officialGate.canEnterPhase11B]) !== JSON.stringify(['SOURCE-BLOCKED',26,1,1,0,'ISSUE-P0-002',0,false,false])) errors.push('official gate regression');
const verifiedImplementationHead=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const evidence = { schemaVersion:'phase11a3-community-reference-final-acceptance.v1', runId:randomUUID(), measuredAt:new Date().toISOString(), verifiedImplementationHead, evidencePublicationParent:verifiedImplementationHead, inputPackageSha256:inputHash, committedArtifactHashes, regeneratedArtifactHashes, regenerationParity, derivedCounts:{requirements:metrics.requirements,fields:metrics.fields,eligible:metrics.eligible,unresolved:metrics.unresolved}, sourceReferences:{total:metrics.sourceReferences,resolved:metrics.resolvedSourceReferences,unresolved:metrics.sourceReferences-metrics.resolvedSourceReferences}, bindings:{expected:metrics.expectedBindings,actual:metrics.actualBindings,unbound:metrics.unbound,unexpected:metrics.unexpected}, typedProjections:{quests:COMMUNITY_DATASET.quests.length,guardians:COMMUNITY_DATASET.guardians.length,rooms:COMMUNITY_DATASET.rooms.length,dungeonTiles:metrics.tiles,finalEncounter:COMMUNITY_DATASET.finalEncounter.length,monsterPhysical:metrics.monsterPhysical,monsterLogical:metrics.monsterLogical}, blockedFields, adversarialTests:{expected:22,run:22,passed:commands.adversarialTests.exitCode===0?22:0}, typecheckPasses:commands.typecheck.exitCode===0, commands, officialGate, terminalVerdict:errors.length===0?'COMMUNITY-REFERENCE-DATA-BOUND':'COMMUNITY-REFERENCE-DATA-BINDING-BLOCKED', errors };
writeFileSync(join(root,'community-reference-binding-evidence.json'),JSON.stringify(evidence,null,2)+'\n'); rmSync(temp,{recursive:true,force:true});
console.log(JSON.stringify(evidence,null,2)); if(errors.length) process.exit(1);
