import {expect,test,type Page} from '@playwright/test';
import {readFileSync,appendFileSync,writeFileSync} from 'node:fs';
import type {CampaignState,SaveFile} from '../src/types';
const fixtures=JSON.parse(readFileSync('pw-out/c2e-browser-fixtures.json','utf8'));
const observations:Array<{point:string;phase:string|null;rngCalls:number;rngCursor:number;clockCursor:number;idCursor:number;rolls:number[];targetIds:string[];candidateIds:string[];effectIds:string[];deferredIds:string[]}> = [];
const network=new Map<Page,{title:string;externalRequests:string[];appErrors:string[];sourceModuleRequests:string[]}>();
test.beforeEach(async({page},info)=>{const receipt={title:info.title,externalRequests:[] as string[],appErrors:[] as string[],sourceModuleRequests:[] as string[]};network.set(page,receipt);page.on('pageerror',e=>receipt.appErrors.push(e.message));page.on('request',r=>{if(/\/(src|@vite|@react-refresh)\//.test(r.url()))receipt.sourceModuleRequests.push(r.url());});await page.route('**/*',route=>{const url=route.request().url();if(!url.startsWith('http://localhost:5199/')&&!url.startsWith('http://127.0.0.1:5199/')){receipt.externalRequests.push(url);return route.abort();}return route.continue();});});
test.afterEach(async({page})=>{const receipt=network.get(page)!;appendFileSync('pw-out/c2e-browser-network.jsonl',JSON.stringify(receipt)+'\n');expect(receipt.appErrors).toEqual([]);expect(receipt.externalRequests).toEqual([]);expect(receipt.sourceModuleRequests).toEqual([]);});
async function saved(page:Page):Promise<CampaignState> {return page.evaluate(()=>JSON.parse(localStorage.getItem('dd-web-prototype-save-v1')!).campaign);}
async function reload(page:Page,point:string) {const before=await saved(page);writeFileSync('pw-out/c2e-last-checkpoint.json',await page.evaluate(()=>localStorage.getItem('dd-web-prototype-save-v1')!));await page.reload();await expect(page.getByTestId('save-broken')).toHaveCount(0);expect(await saved(page)).toEqual(before);const s=before.heroProductionSession,p=s?.pendingAction;const observation={point,phase:p?.phase??null,rngCalls:s?.rngCalls??0,rngCursor:s?.rngCursor??0,clockCursor:s?.clockCursor??0,idCursor:s?.idCursor??0,targetIds:p?.frozenTargetIds??[],candidateIds:p?.pendingChoice?.candidateIds??[],rolls:p?.storedRolls??[],effectIds:p?.resolvedEffectIds??[],deferredIds:s?.events.filter(e=>e.deferredId).map(e=>e.eventId)??[]};observations.push(observation);appendFileSync('pw-out/c2e-browser-checkpoints.jsonl',JSON.stringify(observation)+'\n');}
async function importSave(page:Page,save:SaveFile) {await page.goto('/');await page.getByRole('link',{name:'首页',exact:true}).click();await page.locator('input[type="file"]').setInputFiles({name:'c2e-prerequisite.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(save))});await expect(page.getByTestId('home-notice')).toContainText('存档导入成功');await page.getByTestId('btn-continue').click();}
async function targets(page:Page,ids?:string[]) {const c=await saved(page),p=c.heroProductionSession!.pendingAction!,t=fixtures.inventory.find((h:any)=>h.heroId===p.heroId).skills.find((s:any)=>s.skillId===p.skillId).targeting[p.face],placements=c.battle!.bossEncounter?.placements??c.battle!.largeMovementContract!.placements,candidates=p.pendingChoice!.candidateIds,units=[...c.battle!.heroes,...c.battle!.monsters],selected=ids??[...new Set(candidates.map(id=>placements[id]))].map(area=>t.groups.flatMap((g:any)=>candidates.filter(id=>placements[id]===area&&units.find(u=>u.id===id)!.side===(g.side==='HERO'?'hero':'monster')).slice(0,g.targetCount.kind==='exact'?g.targetCount.value:1))).find(group=>group.length===t.groups.reduce((n:number,g:any)=>n+(g.targetCount.kind==='exact'?g.targetCount.value:1),0));if(!selected)throw new Error('No legal source target combination');for(const id of selected)await page.getByTestId('target-'+id).check();await page.getByTestId('production-confirm-targets').click();await expect(page.getByRole('alert')).toHaveCount(0);}
async function finish(page:Page,point:string) {for(let n=0;n<60;n++){const c=await saved(page),p=c.heroProductionSession?.pendingAction;if(!p)return;if(p.pendingChoice){if(p.pendingChoice.continuation.kind==='hero-production'&&p.pendingChoice.continuation.field==='targets')await targets(page);else {await reload(page,point+' movement choice');await page.getByTestId('production-movement-choice').first().click();}}else {await page.getByTestId('production-advance').click();await expect(page.getByRole('alert')).toHaveCount(0);if((await saved(page)).heroProductionSession?.pendingAction)await reload(page,point+' step '+n);}}throw new Error('Action exceeded continuation bound');}
async function newParty(page:Page) {await page.goto('/');await page.getByRole('button',{name:'新建战役',exact:true}).click();await expect(page.locator('[data-testid^="choose-"]')).toHaveCount(18);for(const id of ['crusader','highwayman','vestal','abomination'])await page.getByTestId('choose-'+id).click();for(const [id,stance] of [['crusader','aggressive'],['highwayman','defensive'],['vestal','support'],['abomination','ranged']])await page.getByTestId('stance-'+id).selectOption(stance);await page.getByRole('button',{name:'继续（技能配置）',exact:true}).click();}
test('18-Hero selector, four production Heroes, owned source loadout and new campaign reload',async({page})=>{await newParty(page);for(const h of fixtures.inventory.filter((h:{heroId:string})=>['crusader','highwayman','vestal','abomination'].includes(h.heroId))){await page.getByTestId('loadout-hero-'+h.heroId).click();await expect(page.locator('[data-testid^="production-skill-"]')).toHaveCount(7);for(const s of h.skills)await expect(page.getByTestId('production-skill-'+s.skillId)).toContainText(s.name);}await page.getByRole('button',{name:'使用默认配置（全部英雄）',exact:true}).click();const c=await saved(page);expect(c.heroRuntimeSelection?.runtimeVersion).toBe('C2D-HERO-PRODUCTION-RUNTIME-v1');expect(c.heroes.every(h=>h.productionIdentity&&h.equippedSkillIds.length===3)).toBe(true);await reload(page,'new production loadout');await page.getByRole('button',{name:'继续（任务选择）',exact:true}).click();await expect(page.getByTestId('select-production-ruins-v6')).toBeVisible();});
test('normal new campaign starts a source Quest and continues a real ordinary production Skill',async({page})=>{
 await newParty(page);await page.getByRole('button',{name:'使用默认配置（全部英雄）',exact:true}).click();await page.getByRole('button',{name:'继续（任务选择）',exact:true}).click();await page.getByTestId('migrate-hero-dodge-v2').click();await page.getByTestId('select-production-ruins-v6').click();await page.locator('[data-testid^="quest-community-"]').first().click();
 for(let n=0;n<30;n++) {const c=await saved(page);if(c.battle)break;
  const overlay=page.getByTestId('quest-rule-choice');if(await overlay.count()){await overlay.getByRole('button').first().click();continue;}
  const d=c.dungeon!;const target=d.rooms.find(r=>r.sourceRoomToken==='lair'||r.type==='battle')!;const queue:Array<{id:string;path:string[]}>=[{id:d.currentRoomId!,path:[]}],seen=new Set<string>();let path:string[]=[];
  while(queue.length){const v=queue.shift()!;if(v.id===target.id){path=v.path;break;}if(seen.has(v.id))continue;seen.add(v.id);for(const to of d.rooms.find(r=>r.id===v.id)!.adjacentRoomIds)queue.push({id:to,path:[...v.path,to]});}
  if(!path.length)throw new Error('No ordinary Room path');await page.getByTestId('dungeon-room-'+path[0]).click();
  const ack=page.getByTestId('event-confirm');if(await ack.count())await ack.click();
 }
 expect((await saved(page)).battle?.ruinsContext).toBeTruthy();
 for(let n=0;n<60;n++){const choice=page.getByRole('region',{name:'Ruins 待决选择'});if(await choice.count()){await choice.getByRole('button').first().click();continue;}const resolution=page.getByTestId('battle-continue-resolution');if(await resolution.count()){await resolution.click();continue;}const skill=page.locator('[data-testid^="skill-"]:enabled').first();if(await skill.count()){await skill.click();break;}const end=page.getByTestId('end-turn');if(await end.count())await end.click();else {const decline=page.locator('[data-testid^="trinket-decline-"]');if(await decline.count())await decline.first().click();else throw new Error('No ordinary continuation controls');}}
 await expect(page.getByTestId('production-action')).toBeVisible();await reload(page,'new campaign real ordinary target selection');const p=(await saved(page)).heroProductionSession!.pendingAction;if(p?.pendingChoice)await targets(page);await finish(page,'ordinary production');expect((await saved(page)).heroProductionSession!.completedActions.length).toBeGreaterThan(0);await reload(page,'ordinary complete');
});
test('ordinary Monster source fixture continues using production executor',async({page})=>{await importSave(page,fixtures.ordinary);for(let n=0;n<60;n++){const choice=page.getByRole('region',{name:'Ruins 待决选择'});if(await choice.count()){await choice.getByRole('button').first().click();continue;}const resolution=page.getByTestId('battle-continue-resolution');if(await resolution.count()){await resolution.click();continue;}const skill=page.locator('[data-testid^="skill-"]:enabled').first();if(await skill.count()){await skill.click();break;}await page.getByTestId('end-turn').click();}await expect(page.getByTestId('production-action')).toBeVisible();if((await saved(page)).heroProductionSession!.pendingAction?.pendingChoice)await targets(page);await finish(page,'ordinary source fixture');await reload(page,'ordinary source fixture complete');});
test('synthetic checkpoint coverage: multi-target, stored roll and partial effects reload without duplicate receipts',async({page})=>{await importSave(page,fixtures.multi);await page.getByTestId('skill-vestal-divine-comfort-front').click();let p=(await saved(page)).heroProductionSession!.pendingAction!;if(p.pendingChoice)await targets(page,p.pendingChoice.candidateIds);await page.getByTestId('production-advance').click();await reload(page,'multi after roll');await finish(page,'multi partial resolution');const c=await saved(page);expect(c.heroProductionSession!.completedActions[0].frozenTargetIds.length).toBeGreaterThan(1);expect(new Set(c.heroProductionSession!.events.map(e=>e.eventId)).size).toBe(c.heroProductionSession!.events.length);});
test('synthetic checkpoint coverage: player movement destination survives reload',async({page})=>{await importSave(page,fixtures.movement);await page.getByTestId('skill-bounty-hunter-come-hither-front').click();await targets(page);let observed=false;for(let n=0;n<40;n++){const p=(await saved(page)).heroProductionSession?.pendingAction;if(!p)break;if(p.pendingChoice){observed=true;await reload(page,'explicit movement PendingChoice');await page.getByTestId('production-movement-choice').first().click();}else await page.getByTestId('production-advance').click();}expect(observed).toBe(true);await reload(page,'movement completed');});
test('Guild Hero II and III upgrades preserve wounds and render exact source Profile',async({page})=>{await importSave(page,fixtures.guild);await expect(page.getByTestId('guild-policy')).toBeVisible();await page.getByTestId('guild-upgrade-hero-level').click();await page.getByTestId('guild-upgrade-hero-level').click();await reload(page,'Guild pending choices');await page.getByTestId('guild-commit').click();const h=(await saved(page)).heroes[0];expect(h.level).toBe(3);expect(h.maxLife).toBe(32);expect(h.wounds).toBe(3);await reload(page,'Guild Hero III');});
test('Guild Skill II resolves exact definition on later loadout',async({page})=>{const save=structuredClone(fixtures.guild);const h=save.campaign.heroes[0];h.level=2;h.maxLife=24;h.productionIdentity.level=2;h.productionIdentity.sourceBindingId='c2b:crusader:profile:L2:HERO_PROFILE';await importSave(page,save);await page.getByTestId('guild-upgrade-skill-'+h.equippedSkillIds[0]).click();await page.getByTestId('guild-commit').click();expect((await saved(page)).heroes[0].skillLevels[h.equippedSkillIds[0]]).toBe(2);await reload(page,'Guild Skill II');const later={...save,campaign:await saved(page)};later.campaign.gamePhase='skill-loadout';await importSave(page,later);await expect(page.getByTestId('production-skill-'+h.equippedSkillIds[0])).toHaveAttribute('data-level','2');});
test('Stagecoach replacement creates an expansion production Hero',async({page})=>{await importSave(page,fixtures.replacement);await page.getByTestId('candidate-musketeer').click();await page.getByTestId('upgrade-hero-level').click();await page.locator('[data-testid^="upgrade-skill-"]:enabled').first().click();await reload(page,'Stagecoach draft');await page.locator('[data-testid^="confirm-replacement-"]').first().click();const c=await saved(page);expect(c.heroes[0].heroId).toBe('musketeer');expect(c.heroes[0].level).toBe(2);expect(c.heroes[0].skillLevels[c.heroes[0].equippedSkillIds[0]]).toBe(2);expect(c.heroes[0].productionIdentity).toBeTruthy();expect(c.heroes[0].equippedSkillIds.every(id=>id.startsWith('musketeer-'))).toBe(true);await reload(page,'Stagecoach commit');});
test('Abomination HUMAN/BEAST restriction and skipped transform remain visible',async({page})=>{await importSave(page,fixtures.abomination);await expect(page.getByTestId('skill-abomination-transform-to-beast-front')).toBeEnabled();await expect(page.getByTestId('skill-abomination-transform-to-beast-back')).toBeDisabled();await page.getByTestId('skill-abomination-transform-to-beast-front').click();await finish(page,'Abomination deferred transform');const c=await saved(page);expect(c.heroes.every(h=>h.productionIdentity!.form==='HUMAN')).toBe(true);expect(c.heroProductionSession!.events.some(e=>e.deferredId==='C2C-DEFER-TRANSFORM-ATOMIC-ORDER')).toBe(true);await expect(page.locator('body')).toContainText('Manual validation pending');await reload(page,'Abomination deferred receipt');});
test('real browser v22 load remains legacy and selectable',async({page})=>{await importSave(page,fixtures.legacy);expect((await saved(page)).heroRuntimeSelection?.runtimeVersion).toBe('LEGACY_HERO_RUNTIME_V1');expect((await saved(page)).heroes.every(h=>!h.productionIdentity)).toBe(true);await expect(page.getByRole('button',{name:'继续（技能配置）',exact:true})).toBeVisible();await reload(page,'legacy migrated v23');await page.getByRole('link',{name:'首页',exact:true}).click();await expect(page.getByTestId('legacy-ruleset')).toContainText('Manual validation pending');await page.getByTestId('btn-continue').click();});

for(const family of ['necromancer','prophet'])test(`real ${family} Boss continues source Hero executor through browser reload`,async({page})=>{
 await importSave(page,fixtures[family]);await expect(page.getByTestId('end-turn')).toBeVisible();const button=page.locator('[data-testid^="skill-"]:enabled').first();await expect(button).toBeVisible();await button.click();await expect(page.getByTestId('production-action')).toBeVisible();await reload(page,family+' target selection');await finish(page,family+' production action');expect((await saved(page)).heroProductionSession!.completedActions.length).toBeGreaterThan(0);await reload(page,family+' action committed');
});
